[project]
name = "chapter02"
version = "0.1.0"
dependencies = [
    "common", # Depends on shared code
]

[tool.uv.sources]
common = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/chapter02"]
